// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Game struct {
	ID   int64
	Name string
}

type GameInfo struct {
	GameID          int64
	ImageUrl        sql.NullString
	InitialPrice    sql.NullFloat64
	FinalPrice      sql.NullFloat64
	DiscountPercent sql.NullFloat64
}

type UsersGame struct {
	GameID int64
	UserID int64
}
